spring:
  datasource:
    # initialize: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/travel_helper
    username: travel_user
    password: somesecurepassword

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 8

  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${google.client.id}
            clientSecret: ${google.client.secret}
            scope: openid,email,profile
        provider:
          google:
            user-name-attribute: name
app:
  auth:
    tokenSecret: A364AE3D35494DA89EA5CA761B7A4A176D769E1010FA41EC9800EBFAC2DBAFE4
    tokenExpirationMs: 864000000