spring:
  datasource:
    # initialize: true
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 8

  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${google.client.id}
            clientSecret: ${google.client.secret}
            scope: openid,email,profile
        provider:
          google:
            user-name-attribute: email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com